# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
#    - shell: bash
#      env:
#        TEST_VALUE: ${{ secrets.TEST_VALUE2 }}
#      run: |
#        echo "$TEST_VALUE"
    - name: Print TEST_VALUE
      run: |
        echo "TEST_VALUE is: $TEST_VALUE"
      env:
        TEST_VALUE: ${{ secrets.TEST_VALUE2 }}
        API_KEY_FOR_TESTS: ${{ secrets.API_KEY_FOR_TESTS }}
        API_KEY: ${{ secrets.API_KEY }}

#    - name: Set API Key for tests for Tests as Environment Variable
#      run: echo "API_KEY_FOR_TESTS=${{ secrets.API_KEY_FOR_TESTS }}" >> $GITHUB_ENV'
#    - name: Set API Key as Environment Variable
#      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Print TEST_VALUE2
      run: |
        echo "TEST_VALUE is: $TEST_VALUE"
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
      env:
        TEST_VALUE: ${{ secrets.TEST_VALUE2 }}
        API_KEY_FOR_TESTS: ${{ secrets.API_KEY_FOR_TESTS }}
        API_KEY: ${{ secrets.API_KEY }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}